### ISSUE TITLE
ngix 500 error

### ISSUE THREAD

**Issue by schealex** [tiredofit/docker-osticket#3]
Hi

i'm trying to use your docker image but i'm always getting a 500 from ngix when i try to access the url of the installation.
Any steps i'm missing?

Regards

**Comment by tiredofit** [comment]
Have a peek at the logs in /www/logs/nginx/error.log and it should give a reason as to why its failing..

**Comment by schealex** [comment]
not really. the log folder does contain logs but they are all empty.

when i check my ngix reverse proxy i see this:

7.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
xxx.xxx.de x.x.121.111 - - [04/Sep/2020:14:17:24 +0000] "GET / HTTP/2.0" 500 595 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"

**Comment by tiredofit** [comment]
Unfortunately the reverse proxy won't tell what script or file is failing yet only pass the 500 value.
50x errors typically relate to something related to the PHP-FPM implementation - either it's misconfigured, or is failing on a specific file. Perhaps access.log might give some tips as well. 

Otherwise, are you able to share the way you are starting the image? Strip of course any domain names/credentials..

**Comment by schealex** [comment]
acceess.log is also empty

I'm also using jrcs/letsencrypt-nginx-proxy-companion for my ngix and proxy setup.
for me it seems like the container is not accepting any connections \o/

this is my compose file:

```
version: '3.3'
services:

  osticket-app:
    image: tiredofit/osticket
    container_name: osticket-app
    volumes:
      - /data/osticket/data/:/www/osticket
      - /data/osticket/logs/:/www/logs
    environment:
      - ZABBIX_HOSTNAME=osticket-app

      - CRON_PERIOD=10

      - DB_HOST=osticket-db
      - DB_NAME=osticket
      - DB_USER=osticket
      - DB_PASS=xxx

      - SMTP_HOST=mail.xxx.de
      - SMTP_PORT=25
      - SMTP_FROM=tickets@xxx.de
      - SMTP_TLS=0
      - SMTP_USER=tickets@xxx.de
      - SMTP_PASS=xxx

      - INSTALL_SECRET=xxx
      - INSTALL_EMAIL=tickets@xxx.de
      - INSTALL_NAME=Helpdesk

      - ADMIN_FIRSTNAME=x
      - ADMIN_LASTNAME=x
      - ADMIN_EMAIL=x@xxx.de
      - ADMIN_USER=x
      - ADMIN_PASS=xxx

      - VIRTUAL_HOST=tickets.xxx.de
      - LETSENCRYPT_HOST=tickets.xxx.de
      - LETSENCRYPT_EMAIL=hostmaster@xxx.de
    networks:
      - nginx-proxy
      - services
    restart: always

  osticket-db:
    image: tiredofit/mariadb
    container_name: osticket-db
    volumes:
      - /data/osticket/db/osticket:/var/lib/mysql
    environment:
      - ROOT_PASS=xxx
      - DB_NAME=osticket
      - DB_USER=osticket
      - DB_PASS=xxx

      - ZABBIX_HOSTNAME=osticket-db
    networks:
      - services
    restart: always

  osticket-db-backup:
    container_name: osticket-db-backup
    image: tiredofit/mariadb-backup
    links:
      - osticket-db
    volumes:
      - /data/osticket/dbbackup:/backup
    environment:
      - DB_HOST=osticket-db
      - DB_TYPE=mariadb
      - DB_NAME=osticket
      - DB_USER=osticket
      - DB_PASSWORD=xxx
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
    networks:
      - services
    restart: always

networks:
  nginx-proxy:
    external: true
  services:
    external: true
```
