### ISSUE TITLE
Example docker-compose.yml formatting error

### ISSUE THREAD

**Issue by jcommander** [tiredofit/docker-osticket#32]
The example docker-compose.yml accidentally introduced an empty `labels` key

```
version: '3.7'
services:

  osticket-app:
    image: tiredofit/osticket
    container_name: osticket-app
    labels:
    labels:
      - traefik.enable=true
```

Running it will throw the following error:
```
>docker compose up
parsing .\docker-compose.yml: yaml: unmarshal errors:
  line 8: mapping key "labels" already defined at line 7
```
